{
    "name": "Library Management",
    "summary": "Manage library catalog",
    "author": "JAG, Javier Antó Garcia, Odoo Community Association (OCA)",
    "license": "AGPL-3",
    "website": "https://github.com/javierobcn/jag-odoo-modules",
    "version": "18.0.0.0.2",
    "category": "Services/Library",
    "depends": [
        "base",
        "contacts",
        "web",
        "product",
        "stock",
        "website",
        "website_blog",
    ],
    "data": [
        "security/library_security.xml",
        "security/ir.model.access.csv",
        "views/res_partner_views.xml",
        "views/book_genre_views.xml",
        "views/product_template_views.xml",
        "views/jag_library_menu_views.xml",
        "views/blog_post_views.xml",
        "views/blog_post_book_template_views.xml",
        "views/res_config_settings_views.xml",
        "views/website_blog_post_title_style_views.xml",
    ],
    "application": True,
}
